# Oldest compatible system. Example: era=winxp/win7/win10 (on Windows), era=10.14 (on macOS)
if(APPLE)
  set(CMAKE_OSX_DEPLOYMENT_TARGET "%era%" CACHE INTERNAL "")
elseif(WIN32)
  string(TOUPPER "%era%" WIN32_WINNT_MACRO)
  string(APPEND CMAKE_C_FLAGS_INIT " -D_WIN32_WINNT_=${WIN32_WINNT_MACRO}")
  string(APPEND CMAKE_CXX_FLAGS_INIT " -D_WIN32_WINNT_=${WIN32_WINNT_MACRO}")
endif()
